swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0

host: 0.0.0.0
basePath: /v1
schemes:
  - https

paths:
  /classify/{image_path}:
    get:
      summary: Returns a dict for classify result.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      parameters:
      - in: "path"
        name: "image_path"
        description: "Picture folders that need to be predicted"
        required: true
        type: "string"
      responses:
        200:
          description: OK
        400:
          description: "Invalid Image_path supplied"
        404:
          description: "image_path not found"